### PR TITLE
Fix node next tick

### PR DESCRIPTION
**Pull request by stefanpenner**
cc @SSS2557 I suspect this will fix the issue we saw, mind confirming on you repo?

### CODE REVIEW

**Comment by sandesh-shastry** [comment]
right on! :zap:  
This fixes that recursive issue resulting in max call stack exceeded error :) 

Thanks!

**Comment by sandesh-shastry** [comment]
@ef4 , this will help all those node 10 users still left out there :)

**Comment by ef4** [comment]
Published in 1.0.0.

**Comment by stefanpenner** [comment]
:+1:

**Pull request merged**
