### PR TITLE
Upgraded fast-sourcemap-concat to 0.2.4 to fix issue reported in ember-cli

### PR DESCRIPTION
**Pull request by taras**
Hoping it will help us push out fix to https://github.com/ember-cli/ember-cli/issues/3098#issuecomment-74359080 sooner.

### CODE REVIEW

**Comment by ef4** [comment]
Isn't this effectively a no-op?

The "^" already covers 0.2.4.

**Comment by stefanpenner** [comment]
@ef4 lets not trust npm :P (if its cached or local, it will be fine with the old one...)

**Comment by ef4** [comment]
Fair point.

**Comment by ef4** [comment]
Released as 0.4.4.

**Comment by stefanpenner** [comment]
:+1:

**Comment by stefanpenner** [comment]
@taras wanna propagate the change to ember-cli?

**Pull request merged**
