### PR TITLE
Update to broccoli-caching-writer 2.0.0

### PR DESCRIPTION
**Pull request by joliss**
This is a backwards-compatible change - you can push it as a micro release.

I moved all indentation changes into a separate "dedent" commit so it's easier to read the diff.

### CODE REVIEW

**Comment by joliss** [comment]
When you merge this, can we get a new release as well please?

**Comment by stefanpenner** [comment]
@joliss major or minor release?

**Comment by stefanpenner** [comment]
``` sh
➜  broccoli-sourcemap-concat git:(master) git tag v1.1.0
➜  broccoli-sourcemap-concat git:(master) git push origin v1.1.0
npm publish
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:ef4/broccoli-sourcemap-concat.git
 * [new tag]         v1.1.0 -> v1.1.0
➜  broccoli-sourcemap-concat git:(master) npm publish
+ broccoli-sourcemap-concat@1.1.0
```

**Comment by stefanpenner** [comment]
this appears to be crashing for me, when attemping to use it on the ember-cli/stress-app

WIll take a look.

stack for reference:

```
version: 1.13.8-master-5e5d767411
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at /Users/stefanpenner/src/ember-cli/node_modules/broccoli-sourcemap-concat/simple-concat.js:68:64
    at Array.forEach (native)
    at SimpleConcat.build (/Users/stefanpenner/src/ember-cli/node_modules/broccoli-sourcemap-concat/simple-concat.js:66:22)
    at /Users/stefanpenner/src/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:105:21
    at lib$rsvp$$internal$$tryCatch (/Users/stefanpenner/src/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/stefanpenner/src/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/stefanpenner/src/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/stefanpenner/src/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

**Comment by stefanpenner** [comment]
looks like we are missing rebind to the outer this [here](https://github.com/ef4/broccoli-sourcemap-concat/blob/master/simple-concat.js#L69)

**Comment by stefanpenner** [comment]
i think https://github.com/ef4/broccoli-sourcemap-concat/pull/16 fixes it, confirming

**Comment by joliss** [comment]
Thanks!

**Comment by stefanpenner** [comment]
Yup fixed, still need to backfill a test but don't have cycles right now. opening tracking issue https://github.com/ef4/broccoli-sourcemap-concat/issues/17

**Comment by stefanpenner** [comment]
This may have regressed `SimpleCat` in two ways:
1. rebuild time has jumped 400ms -> 3500ms on ember-cli/stress-app
2. annotation/description has been lost (likely just the annotation change)

before:

```
Build successful - 5876ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Funnel: App JS Files                          | 1633ms
SassCompiler                                  | 1572ms
BroccoliMergeTrees                            | 944ms
Concat: App                                   | 448ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Funnel: App JS Files (1)                      | 1633ms
SassCompiler (1)                              | 1572ms
BroccoliMergeTrees (14)                       | 969ms (69 ms)
Concat: App (1)                               | 448ms
Babel (13)
```

after:

```
Build successful - 8587ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SimpleConcat                                  | 3458ms
SassCompiler                                  | 1716ms
```

**Comment by joliss** [comment]
Hm, that's not good. I'll go get some sleep now but will investigate on the weekend.

I'm only using a bare-bones newly generated app at the moment. Do you have a bigger app that I can clone to check performance?

**Comment by joliss** [comment]
Re annotation: Ah yes, we should change the option from `description` to `annotation`. Will send with the next PR.

**Comment by stefanpenner** [comment]
> ember-cli/stress-app

**Comment by stefanpenner** [comment]
@joliss no worries, i suspect not many are using this tonight. I'll most likely take a look and sort it out after dinner.

**Comment by stefanpenner** [comment]
```
DEBUG="broccoli-caching-writer* ember s
```

yields

```
  broccoli-caching-writer:SimpleConcat rebuild { stats: 91042, files: 91041, inputPaths: [ '/Users/stefanpenner/tmp/slow-ember-cli-project/tmp/simple_concat-input_base_path-F9r0uUXS.tmp/0' ] } in 1829ms +2s
```

which indicates, we are likely missing the more constrained stat optimization I made some time ago. In your defense, it was a quick-fix likely easy to regress.

**Comment by stefanpenner** [comment]
This is the same o rebuild:

```
  broccoli-caching-writer:SimpleConcat rebuild { stats: 91042, files: 91041, inputPaths: [ '/Users/stefanpenner/tmp/slow-ember-cli-project/tmp/simple_concat-input_base_path-F9r0uUXS.tmp/0' ] } in 1760ms +0ms
```

**Comment by stefanpenner** [comment]
I'll restore the annotation/descriptions first, as that will make debugging likely trivial.

**Comment by stefanpenner** [comment]
brb food time

**Comment by stefanpenner** [comment]
annotations fixed: https://github.com/ember-cli/ember-cli/pull/4829 (just callers needed to be updated)

now with annotation it appears: ->

```
  broccoli-caching-writer:SimpleConcat > [Concat: App] rebuild { stats: 91042, files: 91041, inputPaths: [ '/Users/stefanpenner/tmp/slow-ember-cli-project/tmp/simple_concat-input_base_path-uTQ4HUn0.tmp/0' ] } in 26
```

looking

**Comment by stefanpenner** [comment]
performance is actually unrelated to this. I guess it has just been some time since I ran the stress app.

It turns out to be https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1029
Which causes some grief if bower_components is massive, but improves performance is bower_components is small but the app is big.

So I thought of a better solution, we can improve the stating / walking logic for BCW, thereby benefiting from both improvements.

Will continue here -> https://github.com/ember-cli/broccoli-caching-writer/pull/57

**Comment by stefanpenner** [comment]
everything i noticed is now addressed, carry on :)

**Pull request merged**
